### ISSUE TITLE
The Roadmap is empty whilst there are plenty of things to do

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#2]
Formulate:
- [x] Mission
- [x] Sustainability and business model
- [x] Governance model
- [x] City partner proposition
- [x] Implementation partner proposition
- [x] Form board of advisors
- [x] Website
- [x] Team on website
- [x] Advisors and ambassadors on website
- [x] Mapping and defining the relationships with others in this field

Then
- [x] Ask @chartgerink to help thinking about structuring these and making them more accessible after making some issues.
