### ISSUE TITLE
Updating membership content on About > Activities [big issue]

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#616]
Updating membership content on About > Activities

- [x]  Add new content on [Membership Process](https://hackmd.io/fAEK_CulTO2oH1dinSzEXg) to "Member Relations" page See #618 

- [x] Add "Stakeholder Engagement" page with new stakeholder definitions [Stakeholder Engagement](https://hackmd.io/3ikgA_8OSOCxWeix6y4i7w) See #619. Fixes #499, #496  

- [x] Update [Membership Growth](https://about.publiccode.net/activities/membership-growth/) page See #620 
- remove old links; add disclaimer to old links; move them to "Further reading" sections
- rewrite how to become a member Step 2
- update Further Reading links

- [x] Add OUTDATED disclaimers to: See #621
- [Membership onboarding support](https://about.publiccode.net/activities/membership-growth/member-onboarding-support.html)
- [Founding membership proposal template](https://about.publiccode.net/activities/membership-growth/founding-membership-proposal.html)

- [x] Create new template for contract based on content of: See #622
- [Member onboarding proposal](https://docs.google.com/document/d/1G-pOyoMvHCjSzMt8YiI6dj7tmP4v9Mbd9sthTyM9pCA/edit)
- [Founding membership proposal template](https://docs.google.com/document/d/1G-pOyoMvHCjSzMt8YiI6dj7tmP4v9Mbd9sthTyM9pCA/edit)
- This new template will become part of membership contracting step, and serve as a cover/TOR of the contract

- [x] Create new template for Expressions of Interest for: See #617 
- Public Partners
- Affiliates

---

**Comment by felixfaassen** [comment]
@lscheske  I noticed your update as I'm a newbie and thinking of ways how to integrate my new knowledge about the foundation, what we do, what our added value is etc. As I have yet to study the about site more deeply I just want to share you my experience as someone who is relatively new to the foundation. 

It think the member onboarding proposal document is excellent. It is very concise, very clear and really helped me as a newcomer to instantly understand the full scope of the Foundation. The issue, our purpose, the problem, the solution and our added value. 

My personal view is that I think this type of  content could also have a great place on the mainpage of our website, in a modified form. What I mean by that is maybe we can add a FAQ section which includes the same sections as in the onboarding proposal like and modify it a bit to suit it more general.

I wonder what @clausmullie and @bvhme think about having an FAQ on based on the info in the membership proposal

**Comment by bvhme** [comment]
Hey @lscheske, I see quite a few points to have some discussions on, perhaps this big issue can sprout some smaller issues? Then you can make this into a checklist and link the issue numbers making this an overview issue.

**Comment by lscheske** [comment]
Thanks @felixfaassen. That is a really good point. I agree that the member onboarding proposal document has really good information. We will not get rid of this, but I intend to recycle some of this for the "public" website (see http repo), so that the content is more accessible to stakeholders.

@bvhme oh yes, great idea, I will break it down!

**Comment by clausmullie** [comment]
This would also close #485
